# docker-compose에는 버전이 존재하며 본 파일에서는
# 3 버전을 사용함.
# 만일 이 파일을 사용하기 위해선 docker-compose 3 버전
# 설치법을 검색하여 설치해야함.
version: '3'

# docker-compose.yml의 서비스들이 아래와 같음.
services:

    ################
    ##### TEST #####
    ################
    super_test:
        # 현재 폴더에서 superdocker 폴더에 있는 Dockerfile을 이용하여
        build: ./superdocker
        # name: super, tag: test인 image를 생성하고 실행하겠음.
        image: super:test

        # super_test를 실행하기 위해선 front_test service가 필요하기
        # 때문에 front_test도 실행하겠음.
        #depends_on:
        #    - front_test
        
        # 현재 경로의 특정 폴더를 컨테이너 내부의 특정 폴더로
        # Mount 하겠음.
        volumes:
            - ~/Product/Main_Server:/home/Main_Server
        # 외부에서 30100 포트로 접근하면
        # 내부에서 3002  포트로 포워딩해줌.
        ports:
            - "30100:3002"

        # 컨테이너가 실행 시 자동으로 실행되는 명령어들
        # entrypoint 대신 command를 사용
        # 아래의 명령어들은 각 팀별 README.md에 작성된 명령어를
        # 경로만 올바른 경로로 변경한 채 나머지는
        # README.md와 동일하게 수행함.
        command:
            - /bin/bash
            - -c
            - |
                cd /home/Main_Server
                npm install && npm run build
                npm run copy-view && npm start

    front_test:
        build: ./frontdocker
        image: front:test2

        volumes:
            - ~/Product/Layout:/home/Layout

        ports:
            - "30300:3000"

        command:
            - /bin/bash
            - -c
            - |
                cd /home/Layout
                npm install && npm start
                

    ##################
    ##### STABLE #####
    ##################
    super:
        build: ./superdocker
        image: super:stable

        volumes:
            - ~/Product/Main_Server:/home/Main_Server
        ports:
            - "30001:3002"
        command:
            - /bin/bash
            - -c
            - |
                cd /home/Main_Server
                npm install && npm run build
                npm run copy-view && npm start
    front:
        build: ./frontdocker
        image: front:stable

        volumes:
            - ~/Product/Layout:/home/Layout
        ports:
            - "30000:3000"
        command:
            - /bin/bash
            - -c
            - |
                cd /home/Layout
                npm install && npm run build
                cd LIVE
                npm install && npm run start
